### ISSUE TITLE
No RSS content

### ISSUE THREAD

**Issue by wangfengze** [monnierant/obsidian-simple-rss#10]
Thank you for developing the plugin. This is exactly what I need. Only one issue: there is almost everything about the feed in variables, but just no content of the article. Is this a bug or by design? Thank you.

**Comment by monnierant** [comment]
It's probably a bug. Can you provide me a rss exemple where you got the issue ?

I'm working on a future version where everyone can use custom property for the feed so it will be ultimately corrected by this future version if it's not a bug on my part.

**Comment by scbarton** [comment]
I attached one of my feeds with the content field. Thanks for working on this!

[feedbin stars.rss.txt](https://github.com/monnierant/obsidian-simple-rss/files/13703503/feedbin.stars.rss.txt)

**Comment by monnierant** [comment]
I will have a look on this thanks for the rss exemple

**Comment by monnierant** [comment]
Hi Issue solved in the last release. https://github.com/monnierant/obsidian-simple-rss/releases/tag/0.3.12

It was due to `\n` or `\n` characters in the title. I have sanityze them.
