### ISSUE TITLE
Format publication date

### ISSUE THREAD

**Issue by infamuze** [monnierant/obsidian-simple-rss#12]
The item.pubdate seems to be a string once I open a note in Obsidian created from an RSS feed. I want to be able to use the item date in Dataview. Can I format it some way?

**Comment by monnierant** [comment]
Hi It's a string format that come from the RSS. I will check if i can do some parsing to a more usable format

**Comment by monnierant** [comment]
Hi i have generalized the collect of rss feed. There is no way actually to add parsing of fields.
