### ISSUE TITLE
Chiming in on the missing Description issue

### ISSUE THREAD

**Issue by Unvented9039** [monnierant/obsidian-simple-rss#15]
I'm also not getting the description. I only tried with the default template. I've tried several feeds and descriptions were not included in each case. For example, https://www.mentalfloss.com/rss.xml

Some feeds don't seem to work at all, such as http://hotword.dictionary.com/?feed=rss2 which does work in Feedly.

**Comment by monnierant** [comment]
For https://www.mentalfloss.com/rss.xml the issue is solved in the last release.

You need to create a custom type of field and add the `description` field to item.

Then you could use `{{&item.description}}` to get it.

**Comment by monnierant** [comment]
For http://hotword.dictionary.com/?feed=rss2 the url give a redirection.

When i try to open the link in my browser it redirect imediately and doesn't stay on the xml field.

The library that i use `rss-parser` act as a webbrowser to collect rss (usefull for youtube rss for exemple).

So as for now i can't fix the issue.
