### ISSUE TITLE
Not Work for RssHub feeds.

### ISSUE THREAD

**Issue by aoout** [monnierant/obsidian-simple-rss#6]
![image](https://github.com/monnierant/obsidian-simple-rss/assets/60838705/ddfd7e75-0aab-4a86-a585-b6e1891d63e8)

I use the same link, which can be opened in the browser, but in the plugin, I will encounter the above error.

**Comment by monnierant** [comment]
Hi i see that you have closed the issue. may i ask what was the cause of it ? maybe i can do some improvements.

**Comment by aoout** [comment]
> Hi i see that you have closed the issue. may i ask what was the cause of it ? maybe i can do some improvements.

Thanks. I have forked your repo and fixed it.
